# Generated by Django 5.0.6 on 2024-05-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='services_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=28)),
                ('staff_image', models.ImageField(blank=True, null=True, upload_to='staffs_images/')),
                ('position', models.CharField(choices=[('Director', 'director'), ('Marketing Manager', 'marketing_manager'), ('Selles Manager', 'selles_manager'), ('HR', 'hr')], max_length=60)),
            ],
        ),
    ]
